apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    k8s-app: ks-sample-dev
    qcloud-app: ks-sample-dev
  name: ks-sample-dev
  namespace: kubesphere-sample-dev2
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      k8s-app: ks-sample-dev
      qcloud-app: ks-sample-dev
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: ks-sample-dev
        qcloud-app: ks-sample-dev
    spec:
      containers:
      - env:
        - name: PATH
          value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
        - name: LANG
          value: C.UTF-8
        - name: JAVA_VERSION
          value: "8"
        - name: JAVA_UPDATE
          value: "202"
        - name: JAVA_BUILD
          value: "08"
        - name: JAVA_PATH
          value: 1961070e4c9b4e26a04e7f5a083f551e
        - name: JAVA_HOME
          value: /usr/lib/jvm/default-jvm
        - name: SPRING_PROFILES_ACTIVE
        image: qsharbor.tencentcloudcr.com/java/devops-java-test:SNAPSHOT-k8s-demo--53
        imagePullPolicy: IfNotPresent
        name: ks-sample-dev
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 256Mi
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
---
apiVersion: v1
kind: Service
metadata:
  managedFields:
  - apiVersion: v1
    manager: tke-apiserver
    operation: Update
  name: ks-sample-dev
  namespace: kubesphere-sample-dev2
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: ks-sample-dev
    nodePort: 30088
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    k8s-app: ks-sample-dev
    qcloud-app: ks-sample-dev
  type: NodePort